version: '3.1'
services:
  nginx:
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:80"
    networks:
      - front-tier
    restart: unless-stopped

  boards-api:
    env_file:
      - ./env/common.env
      - ./env/boards-api.env
    expose:
      - "80"
    depends_on:
      - boards-db
    networks:
      - front-tier
      - back-tier
    restart: unless-stopped

  boards-db:
    env_file:
      - ./env/boards-api.env
    volumes:
      - ${PROJECT_DATA_DIR}/boards-db:/var/lib/postgresql/data
      - ${PROJECT_BACKUP_DIR}/boards-db:/var/lib/postgresql/backup
    networks:
      - back-tier
    restart: unless-stopped

  sshd:
    ports:
      - "${SSHD_PORT}:22"
    networks:
      - front-tier
      - back-tier
    restart: unless-stopped

networks:
  front-tier:
  back-tier:
